// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmWS5_TXzXcv4u4b1jGZNxqRfCtcn5qA8',
    appId: '1:223289814112:web:f54dfc59eb29b6c00ea705',
    messagingSenderId: '223289814112',
    projectId: 'onurreklam-83f58',
    authDomain: 'onurreklam-83f58.firebaseapp.com',
    storageBucket: 'onurreklam-83f58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWugLccxh0p2gmEXOQjdIqPbcdZx4kDsQ',
    appId: '1:223289814112:android:7713994dd1219fcb0ea705',
    messagingSenderId: '223289814112',
    projectId: 'onurreklam-83f58',
    storageBucket: 'onurreklam-83f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1ckxY5t5hMf9jvfYT48LF1FlUer8WUg',
    appId: '1:223289814112:ios:15d0fe7b9cd181250ea705',
    messagingSenderId: '223289814112',
    projectId: 'onurreklam-83f58',
    storageBucket: 'onurreklam-83f58.appspot.com',
    iosClientId: '223289814112-46gdgkap7hpcedq947kjh32asb7jmbq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.onurReklam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1ckxY5t5hMf9jvfYT48LF1FlUer8WUg',
    appId: '1:223289814112:ios:15d0fe7b9cd181250ea705',
    messagingSenderId: '223289814112',
    projectId: 'onurreklam-83f58',
    storageBucket: 'onurreklam-83f58.appspot.com',
    iosClientId: '223289814112-46gdgkap7hpcedq947kjh32asb7jmbq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.onurReklam',
  );
}
